### ISSUE TITLE
Missing pty.h on macOS

### ISSUE THREAD

**Issue by soveran** [deadpixi/mtm#6] opened 2017-02-25 16:30 UTC
It could be a mistake on my part, but I'm encountering this error.

```console
$ make
cp -i config.def.h config.h
gcc -O3 -std=c99 -Wall -Wno-unused-variable -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE_EXTENDED -DTMT_HAS_WCWIDTH -o mtm -DNCURSESW_INCLUDE_H="<ncursesw/curses.h>" tmt.c mtm.c  -lncursesw -lutil
mtm.c:19:10: fatal error: 'pty.h' file not found
#include <pty.h>
         ^
1 error generated.
make: *** [mtm] Error 1
$ 
```

**Comment by deadpixi** [comment] 2017-02-25 16:32
Hi @soveran 

Could you replace <pty.h> with <util.h> and try the compile again?

**Comment by soveran** [comment] 2017-02-25 17:17
Now it can't find `ncursesw`

```terminal
$ make
gcc -O3 -std=c99 -Wall -Wno-unused-variable -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE_EXTENDED -DTMT_HAS_WCWIDTH -o mtm -DNCURSESW_INCLUDE_H="<ncursesw/curses.h>" tmt.c mtm.c  -lncursesw -lutil
mtm.c:28:10: fatal error: 'ncursesw/curses.h' file not found
#include NCURSESW_INCLUDE_H
         ^
<command line>:4:28: note: expanded from here
#define NCURSESW_INCLUDE_H <ncursesw/curses.h>
                           ^
1 error generated.
make: *** [mtm] Error 1
$ 
```

**Comment by deadpixi** [comment] 2017-02-25 17:30
From my initial Googling it looks like macOS doesn't include ncursesw by default. Please try replacing that whole line with just "#include <curses.h>" and see what happens.

If worse comes to worst, you might need to install ncursesw via one of the macOS package managers like Homebrew.

**Comment by soveran** [comment] 2017-02-25 20:27
I replaced two lines in `Makefile`:

```diff
-HEADERS  ?= -DNCURSESW_INCLUDE_H="<ncursesw/curses.h>"
+HEADERS  ?= -DNCURSESW_INCLUDE_H="<curses.h>"
-LIBS     ?= -lncursesw -lutil
+LIBS     ?= -lncurses -lutil
```

And one line in `mtm.c`:

```diff
-#include <pty.h>
+#include <util.h>
```

Now it works (I can split the screen, display unicode, etc.), but then in the prompt it prepends the string `]0;mtm`. Even if I clear the screen, some applications fail to display correctly. If it's something you think can be fixed easily, let me know. Otherwise I will investigate some more about `ncursesw`.

Thanks!

**Comment by deadpixi** [comment] 2017-02-25 20:35
Thanks for all the testing. I'm glad to know it's mostly working. I think the next step is to wipe macOS and install Linux. ;)

Seriously, though could you take a screenshot of one of the applications that doesn't render correctly? I'm curious to see exactly what's going on. It might be related to multibyte decoding. What're your LANG/LC_ALL/LC_CTYPE environment variables set to? One or more of them might be empty; that's okay. 

Thank you.

**Comment by soveran** [comment] 2017-02-25 21:49
I'll wait for a nice computer with plan9 :-)

Here are two screenshots:

![mtm-screenshot-1](https://cloud.githubusercontent.com/assets/951/23335028/2b8f8214-fbac-11e6-9c59-9cf0c62ffc16.png)
![mtm-screenshot-2](https://cloud.githubusercontent.com/assets/951/23335027/2b87e7e8-fbac-11e6-8d7c-8a6e30eaeec6.png)

As for the variables: `LC_CTYPE` is set to `UTF-8`, and both `LANG` and `LC_ALL` are empty.

**Comment by deadpixi** [comment] 2017-02-25 23:56
Thanks for the screenshots; I really appreciate your help in debugging. 

Can you let me know the contents of the environment variables that control your shell prompt? For bash, that would be primarily $PS1; if you're using a different shell that would of course be different. 

Could you also please run the "tput cold" command both inside and outside of mtm in the same Terminal window?

Thank you again for your help. I'm really interested in getting this working on the Mac.

**Comment by soveran** [comment] 2017-02-26 00:18
I'm using tcsh:

```csh
set prompt='%B%j%b %~ %B%#%b '
```

Running `tput cols` yields `169` both inside and outside of mtm.

**Comment by deadpixi** [comment] 2017-02-26 03:24
Hey @soveran.

I'm back at a real computer and not looking at it on my phone.

The "]0;mtm" at the beginning of the prompt looks like the tail-end of the xterm escape sequence that is used to set the title; I bet that escape sequence is also recognized by Apple Terminal. My guess is that one of the special tcsh variables like precmd or something is echoing "ESC ]0;`pwd` BEL" before the prompt to set the Apple Terminal's title to the current directory.

mtm doesn't recognize that escape sequence as it's not specified by the "ansi" terminal type that mtm emulates, and so mtm echos the last part of it out. That escape sequence is something that's useful enough though that I might just recognize it specially so that titles can be set.

For the immediate future, if you're willing to continue helping me debug this, I'd recommend either removing whatever tcsh variable/command is echoing that, or just ignore it.

I'm still trying to figure out why the vi/vim display is corrupted, but I'm pretty sure it's unrelated to the prompt issue.

Thanks again for your help. Once this is all done, I'll owe you a beer.

**Comment by soveran** [comment] 2017-02-26 11:38
I got rid of the precmd and with that the first issue is solved. I had it in place for screen, but the plan is to avoid screen in the future.

Outside of mtm, `TERM` is advertised as `xterm-256color` and `TERM_PROGRAM` is `Apple_Terminal`. When I enter mtm, `TERM` is `ansi` and `TERM_PROGRAM` remains unchanged. I tried setting `TERM` to `Apple_Terminal` inside mtm but I got the same display issues.

The program I was using in the screenshot is [vis](https://github.com/martanne/vis). With vim it looks like only the colors are off. I can send you screenshots of vim with and without mtm, would that help?

**Comment by deadpixi** [comment] 2017-02-26 15:19
That would help, thank you. I'll get a copy of vis and see if I can duplicate the problem. 

As an aside, if you like Plan 9 and sam, you might check out https://github.com/deadpixi/sam :)

**Comment by soveran** [comment] 2017-02-26 15:41
vi without mtm:
![vi-without-mtm](https://cloud.githubusercontent.com/assets/951/23341077/89d7901a-fc41-11e6-8743-015a4dd9879c.png)

vi with mtm:
![vi-with-mtm](https://cloud.githubusercontent.com/assets/951/23341076/898f9f94-fc41-11e6-9a47-a722ffe8ab06.png)

I noticed you are working on sam, that's great :-)

I use vis because it has some very nice features from sam combined with modes and a keyboard centric approach from vi. I'm not a big fan of using the mouse, and that's why vis is so appealing to me.

**Comment by deadpixi** [comment] 2017-02-26 15:59
I downloaded vis and I'm seeing various rendering glitches. I'll figure out why it's happening and get those fixed; then I'll move on to the color-in-vim issues. Thanks for your help.

**Comment by soveran** [comment] 2017-02-26 18:42
I get similar issues with tig, a text-mode interface for git. I mention it in case it's easier for you to test.

**Comment by deadpixi** [comment] 2017-02-26 20:10
The rendering issues have something to do with the "rep" capability. When I switch to mtm's older mach/mach-color emulation (which didn't have the rep capability), the problems go away, and when I create a new terminfo entry for ansi, but without the rep capability listed, the problems likewise go away.

**Comment by deadpixi** [comment] 2017-02-26 20:49
@soveran I think it's fixed. There was a bug in the handling of the repeat_character capability. What's interesting is that the tack test didn't expose it. Either way, please try the latest master and please close this ticket if it works for you. Thanks!

**Comment by deadpixi** [comment] 2017-02-26 21:15
Actually, don't close this issue. I still need to fix compilation on macOS out of the box.

Also, for the color issue, please see if the same colors are used if you set your TERM variable to just "xterm" (not "xterm-256color"). The "ANSI" terminal type has only 64 color pairs, versus 32767 pairs for "xterm-256color", so it's possible that the editor is intentionally rendering itself differently to work in the smaller number of color pairs.

**Comment by soveran** [comment] 2017-02-26 21:29
Excellent! I've just tried it and I feel I can already use mtm full time :-)

There's indeed a difference in the colors, and apart from that there's one small issue with a gray square that appears on the bottom right. If I set `TERM` to `"xterm-256color"`, then with mtm I get a reduced palette (the one you can see in the second screenshot). When I set it to `"xterm"`, then without mtm I get the same reduced palette, but with mtm I get some wrong colors (for example, most of the text becomes green).

vis without mtm, xterm-256color :
![vis-without-mtm](https://cloud.githubusercontent.com/assets/951/23343755/c049fdb6-fc70-11e6-8baa-3c877aaad49b.png)

vis with mtm, xterm-256color:
![vis-with-mtm](https://cloud.githubusercontent.com/assets/951/23343752/adeb62ae-fc70-11e6-995d-fff479f37f57.png)

As for the compilation, after those changes we discussed before I didn't have to modify anything else. If there's anything else you would like me to try, just let me know. Thanks a lot!

**Comment by deadpixi** [comment] 2017-02-27 06:39
The gray square in the corner is your cursor. It looks like vis emulates a separate cursor (cursors? I dunno if it does the multiple cursor thing) using reverse video. Looking at the vis source code, it attempts to hide the hardware (i.e. mtm) cursor using ncurses's set_curs, but that fails because the "ansi" terminal type doesn't specify sequences to hide/show the cursor.

I've added the code to respond to the classic ANSI/ECMA/VT2XX sequences to show and hide the cursor in mtm, but that won't fix vis, since it will still try to clear it using the strings specified in terminfo and fail. I've confirmed by changing the TERM variable to "xterm" and running vis with the new code that the gray square is gone...however that's not a long-term solution.

I'll figure something out on that front. I still need to look into the colors thing too.

**Comment by soveran** [comment] 2017-02-27 08:28
Excellent, thanks a lot! Keep in mind that mtm is usable for me now, so if you have to leave this issue dormant that's OK to me. There's another small issue with vis+mtm for which I have a workaround, but I'll mention it just in case there's an easy fix (or maybe you need to try it too). In vis, `<C-j>` lets you create a new cursor on the line below, and `<C-k>` creates a new cursor on the line above. In mtm,  when I press `<C-j>` vis receives just `<Enter>`, which is understandable. My workaround was to map `<Enter>` in normal mode to `<cursor-new-lines-below>`, and so far I haven't found an undesirable side effect for that setting.

**Comment by deadpixi** [comment] 2017-03-08 14:39
Hi @soveran. My apologies for the sudden silence; I was called out of town unexpectedly for work. 

I just committed a bunch of changes, including stuff that should let mtm compile out of the box on macOS. Would you be so kind as to try the latest master and see if it compiles without changes on the Mac?

I'm afraid I don't think changing the behavior of enter is possible, but I've got an experiment I'd like to try. 

Thanks again for all your help.

**Comment by soveran** [comment] 2017-03-08 15:13
Hey, no problem! I just tried it and I only had to change one line in `Makefile`:

```diff
-LIBS     ?= -lncursesw -lutil
+LIBS     ?= -lncurses -lutil
```

Don't worry about the behavior of enter: the workaround is good enough.

Thanks!

**Comment by deadpixi** [comment] 2017-03-09 06:04
@soveran I just added some documentation and a bit of code to the Makefile for macOS; I think everything should be good now. I'm going to close this ticket now, but please open another ticket if you have any other issues. Thanks again for your help.

PS> I'd be more than happy to add you to the README file in a "Credits" section or something. Please let me know if and how you'd like to be named.

**Closed by deadpixi** 2017-03-09 06:04 UTC
