### ISSUE TITLE
Conflicts with zsh

### ISSUE THREAD

**Issue by fennecdjay** [deadpixi/mtm#8] opened 2017-02-27 01:16 UTC
Thank you for the nice software. However, It looks like there is a bug with zsh:
a `h` (sometimes followed by a `l`) appears after the prompt.
I'd gladly help if given any hint where to look first.

**Comment by deadpixi** [comment] 2017-02-27 06:32
Hi @fennecdjay 

I'm betting the "h" and "l" are the tail-end of something like "ESC [?25h" and "ESC [?25l". Those are escape sequences to make the cursor visible/invisible.  Those particular sequences were ignored by mtm since they weren't specified by the terminfo "ansi" entry.

However, those sequences *are* in the real ANSI spec, and it's reasonable to expect mtm to respond to them, so....now it does. Please download the latest master and see if the problem is fixed. Thanks!

**Comment by fennecdjay** [comment] 2017-02-27 12:02
🎉 
I just pulled and make, and it WORKS!

Thanks you very much.

**Comment by deadpixi** [comment] 2017-03-08 06:14
Hi @fennecdjay, my pleasure. I'm going to close this ticket. Please reopen it if there's still a problem.

**Closed by deadpixi** 2017-03-08 06:14 UTC
